name: ci
on:
  push:
    branches:
      - docker
jobs:
  dockerfile:
    env:
      filename: Dockerfile
      project: santander-phpinfo
      registry: index.docker.io
      tagname: ci
      user: mdearm
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: debug
        run: set -x
      - name: build
        run: docker build --file ${filename} --no-cache --tag ${registry}/${user}/${project}:${tagname} .
      - name: run
        run: docker run --detach --name ${project} ${user}/${project}:${tagname}
      - name: test
        run: while true ; do sleep 10 ; docker logs ${project} 2>&1 | grep started && break ; done
      - name: top
        run: docker top ${project}
      - name: stats
        run: docker stats --no-stream ${project}
      - name: inspect
        run: docker inspect ${project}
      - name: history
        run: docker history index.docker.io/${user}/${project}:${tagname}
